version: '3.3'

services:

  mongodb:
    image: mongo:5.0.8
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - chagas-lab

  api:
    build:
      context: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
    networks:
      - chagas-lab

networks:
  chagas-lab:
    external: true
