version: '3.9'

services:

  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    build:
      context: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    volumes:
      - ./app.py:/app/app.py